//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rep2.Models.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class BackupLog
    {
        public int LogID { get; set; }
        public int SrvBkId { get; set; }
        public string FileName { get; set; }
        public string FilePath { get; set; }
        public System.DateTime DateCreated { get; set; }
        public decimal FileSize { get; set; }
        public bool FileExists { get; set; }
    
        public virtual ServerBackup ServerBackup { get; set; }
    }
}
