//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rep2.Models.EntityModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bGomlaDBreportEntities : DbContext
    {
        public bGomlaDBreportEntities()
            : base("name=bGomlaDBreportEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccessAccount> AccessAccounts { get; set; }
        public virtual DbSet<AccessAccountsType> AccessAccountsTypes { get; set; }
        public virtual DbSet<Artical> Articals { get; set; }
        public virtual DbSet<BackupLog> BackupLogs { get; set; }
        public virtual DbSet<BackupType> BackupTypes { get; set; }
        public virtual DbSet<Branch> Branches { get; set; }
        public virtual DbSet<BranchType> BranchTypes { get; set; }
        public virtual DbSet<DataBaseFile> DataBaseFiles { get; set; }
        public virtual DbSet<DataBaseFilesName> DataBaseFilesNames { get; set; }
        public virtual DbSet<DataBaseFilesSize> DataBaseFilesSizes { get; set; }
        public virtual DbSet<DataBaseServer> DataBaseServers { get; set; }
        public virtual DbSet<Distributer> Distributers { get; set; }
        public virtual DbSet<Machine> Machines { get; set; }
        public virtual DbSet<Publication> Publications { get; set; }
        public virtual DbSet<ServerBackup> ServerBackups { get; set; }
    }
}
