//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rep2.Models.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataBaseFilesSize
    {
        public int SizeID { get; set; }
        public int FileID { get; set; }
        public decimal Size { get; set; }
        public System.DateTime DateTaken { get; set; }
    
        public virtual DataBaseFile DataBaseFile { get; set; }
    }
}
