//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rep2.Models.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataBaseServer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DataBaseServer()
        {
            this.DataBaseFiles = new HashSet<DataBaseFile>();
            this.Distributers = new HashSet<Distributer>();
            this.ServerBackups = new HashSet<ServerBackup>();
            this.Subscribers = new HashSet<Distributer>();
        }
    
        public int ServerID { get; set; }
        public string DataBaseName { get; set; }
        public decimal DataBasePartionFreeSpace { get; set; }
        public int BranchID { get; set; }
        public int DataBaseAccountID { get; set; }
        public int NetworkAccountID { get; set; }
    
        public virtual AccessAccount DBAccount { get; set; }
        public virtual AccessAccount NetworkAccount { get; set; }
        public virtual Branch Branch { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DataBaseFile> DataBaseFiles { get; set; }
        public virtual Machine Machine { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Distributer> Distributers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServerBackup> ServerBackups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Distributer> Subscribers { get; set; }
    }
}
