//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rep2.Models.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataBaseFile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DataBaseFile()
        {
            this.DataBaseFilesSizes = new HashSet<DataBaseFilesSize>();
        }
    
        public int FileID { get; set; }
        public int FileNameID { get; set; }
        public int DbServerID { get; set; }
        public string FilePath { get; set; }
    
        public virtual DataBaseFilesName DataBaseFilesName { get; set; }
        public virtual DataBaseServer DataBaseServer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DataBaseFilesSize> DataBaseFilesSizes { get; set; }
    }
}
