//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rep2.Models.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Machine
    {
        public int MachineID { get; set; }
        public string MachineName { get; set; }
        public string MachineIP { get; set; }
    
        public virtual DataBaseServer DataBaseServer { get; set; }
    }
}
