//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rep2.Models.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServerBackup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ServerBackup()
        {
            this.BackupLogs = new HashSet<BackupLog>();
        }
    
        public int SrvBkID { get; set; }
        public int DbServerID { get; set; }
        public int BackupTypeID { get; set; }
        public int intervalMin { get; set; }
        public string Location { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BackupLog> BackupLogs { get; set; }
        public virtual BackupType BackupType { get; set; }
        public virtual DataBaseServer DataBaseServer { get; set; }
    }
}
